---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/sign_in":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/users/sign_out":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.localhost:8000
