---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/users/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/users/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/users":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/users/sign_in":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/users/sign_out":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
  "/v1/bookings":
    get:
      summary: list bookings
      responses:
        '200':
          description: successful
    post:
      summary: create booking
      responses:
        '200':
          description: successful
  "/v1/bookings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show booking
      responses:
        '200':
          description: successful
    patch:
      summary: update booking
      responses:
        '200':
          description: successful
    put:
      summary: update booking
      responses:
        '200':
          description: successful
    delete:
      summary: delete booking
      responses:
        '200':
          description: successful
  "/v1/cars":
    get:
      summary: list cars
      responses:
        '200':
          description: successful
    post:
      summary: create car
      responses:
        '200':
          description: successful
  "/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show car
      responses:
        '200':
          description: successful
    patch:
      summary: update car
      responses:
        '200':
          description: successful
    put:
      summary: update car
      responses:
        '200':
          description: successful
    delete:
      summary: delete car
      responses:
        '200':
          description: successful
  "/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
